### ISSUE TITLE
How to read output in Realtime?

### ISSUE THREAD

**Issue by RHSaliya** [topjohnwu/libsu#101]
How can I get output in Realtime, suppose I use grep command to find list of files and want to show it as soon as possible. Can I do that?

**Comment by topjohnwu** [comment]
Read the README

**Comment by STICKnoLOGIC** [comment]
Hi! thanks for this great library!
and sorry for opening this issue.

I have face a problem, same in reading output while executing 'read' command..

my exec code is same as the ReadMe stated

I already search on previous issues and discussion with no vail.

the button clicked to exec command:
Shell.getShell().cmd(command.getText().toString())
    .to(callbackList).submit(result -> output.append(result+"\n"));

the command I execute:
cp /storage/emulated/0/welcome.sh /data/data/com.my.newproject6/app_HOME/1.sh && chmod u+x /data/data/com.my.newproject6/app_HOME/1.sh && /data/data/com.my.newproject6/app_HOME/1.sh

1.sh file
`
#!system/bin/sh

read name
echo $name
`

by executing the command using submit will show output
_RET=$?;echo( ...........)unset_RET
then you cant input any command after executing the command above-mentioned.
