### ISSUE TITLE
PING breaks in NO_ROOT_SHELL

### ISSUE THREAD

**Issue by XayahSuSuSu** [topjohnwu/libsu#106]
When I excute commands with no root shell, I cant ping anything and just got this:

`ping: unknown host www.google.com`

But root shell works fine.

What can I do to fix it?

**Comment by osm0sis** [comment]
This is a busybox limitation, you could intentionally use toybox ping instead.

**Comment by XayahSuSuSu** [comment]
> This sounds like a busybox limitation, you could intentionally use toybox ping instead to workaround it.

I didn't use busybox...
All commands connecting network doesn't work, like curl and ping.
But when setting FLAG_MOUNT_MASTER with root, they work fine.

**Comment by osm0sis** [comment]
... libsu includes busybox

**Comment by XayahSuSuSu** [comment]
> ... libsu includes busybox

Oh all right.
And I think I have solved it.

Just because I forgot to add `<uses-permission android:name="android.permission.INTERNET" />`.
So noob am I. lol

Thx anyway!
