### ISSUE TITLE
[Question] How to properly execute root commands with the new cmd API?

### ISSUE THREAD

**Issue by X1nto** [topjohnwu/libsu#109]
In the old shell command execution implementation, we had 2 APIs: `su` and `sh`. Internally, those 2 called `MainShell` with different `su` booleans passed in:
```java
public static Job su(@NonNull String... commands) {
    return MainShell.newJob(/* su = */ true, commands);
}

public static Job sh(@NonNull String... commands) {
    return MainShell.newJob(/* su = */ false, commands);
}
```
Now, the `cmd` method declaration looks like this:
```java
public static Job cmd(@NonNull String... commands) {
    return MainShell.newJob(/* su = */ false, commands);
}
```
As you can see, the `su` parameter is always false.

The question is, how to properly execute root commands if, internally, `MainShell`'s `newJob` always receives the `false` value for the `su` parameter?

My first thought was to add the `su` prefix to the commands (for example, `su getprop`), but I'm not sure how consistent this is across different SU implementations/ROMs.

**Comment by topjohnwu** [comment]
The cmd always sends your commands to the main shell session. It doesn't care whether is is root or not. That's why I have removed the `su` and `sh` API, because it has nothing to do with calling `su`
