### ISSUE TITLE
remount always fails

### ISSUE THREAD

**Issue by UpendraRajput** [topjohnwu/libsu#110]
remounting always fails and none of fileSystem command like rm -rf ,cp ,mv working but all other like reboot and everything working
the very last 4th line of this code try to delete root directory 
i have tried 
Shell.cmd("rm -rf /diretory")  but same results 

see code below 
_____________________________MAIN ACTIVITY __________________________________________
package com.invincible.tool

import android.Manifest
import android.annotation.SuppressLint
import android.app.Activity
import android.content.Intent
import android.os.Build
import android.os.Bundle
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import com.karumi.dexter.Dexter
import com.karumi.dexter.MultiplePermissionsReport
import com.karumi.dexter.PermissionToken
import com.karumi.dexter.listener.PermissionRequest
import com.karumi.dexter.listener.multi.MultiplePermissionsListener
import com.topjohnwu.superuser.Shell
import kotlinx.android.synthetic.main.activity_main.*

class SplashActivity : Activity() {
    companion object {
        init {
            // Set settings before the main shell can be created
            Shell.enableVerboseLogging = BuildConfig.DEBUG
            Shell.setDefaultBuilder(
                Shell.Builder.create()
                    .setFlags(Shell.FLAG_REDIRECT_STDERR)
                    .setTimeout(10)
            )
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // Preheat the main root shell in the splash screen
        // so the app can use it afterwards without interrupting
        // application flow (e.g. root permission prompt)
        Shell.getShell { shell: Shell? ->
            // The main shell is now constructed and cached
            // Exit splash screen and enter main activity
            val intent = Intent(this, MainActivity::class.java)
            startActivity(intent)
            finish()
        }
    }
}

@Suppress("DEPRECATION")
class MainActivity : AppCompatActivity() {
    @SuppressLint("SetTextI18n")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            Dexter.withContext(this)
                .withPermissions(Manifest.permission.MANAGE_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE)
                .withListener(object : MultiplePermissionsListener {
                    override fun onPermissionsChecked(p0: MultiplePermissionsReport?) {
//                            tvlogs.text = "Storage Permission Granted"
//                        Toast.makeText(this@MainActivity,"GRANTED",Toast.LENGTH_SHORT).show()

                    }

                    override fun onPermissionRationaleShouldBeShown(
                        p0: MutableList<PermissionRequest>?,
                        p1: PermissionToken?
                    )
                    {
                    AlertDialog.Builder(this@MainActivity).setTitle("Permission")
                        .setMessage("Permission De BHAI 😒")
                        .setNegativeButton(android.R.string.cancel) { dialogInterface, _ ->
                            dialogInterface.dismiss()
                            p1?.cancelPermissionRequest()
                        }
                        .setPositiveButton(android.R.string.ok) { dialogInterface, _ ->
                            dialogInterface.dismiss()
                            p1?.continuePermissionRequest()
                        }

                    }
                }).check()
        }
        remount()

        btnBanClear.setOnClickListener {
            deletePubg()
            delete_ban_clear_files()
            Toast.makeText(this@MainActivity,"Success",Toast.LENGTH_SHORT).show()
            tvlogs.text = "File Deleted"

        }
        btnCrashFix.setOnClickListener {
            tvlogs.text = deletePubg()}
    }

    companion object {
        // Used to load the 'injector' library on application startup.
        init {
            System.loadLibrary("tool")
        }
    }

//Getting root access++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
private fun remount() {
    if (!Shell.rootAccess()) {
        Toast.makeText(this, "No root access detected", Toast.LENGTH_SHORT).show()
    } else {
        if (Shell.su("mount -o remount,hidpi=2,gid=3009 /proc").exec().isSuccess)
            Toast.makeText(this, "Remount success", Toast.LENGTH_SHORT).show()
        else

            Toast.makeText(this, "Remount Failed", Toast.LENGTH_SHORT).show()
    }
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
}

external fun deletePubg():String

========================== tool.cpp===============================
#include <jni.h>
#include <iostream>
#include <string>
#include <unistd.h>
#include <cstdint>
#include <filesystem>

using namespace std;

extern "C"
JNIEXPORT jstring JNICALL
Java_com_invincible_tool_MainActivityKt_deletePubg(__attribute__((unused)) JNIEnv *env, __attribute__((unused)) jclass clazz) {
    string a;
    a = "I am INVINCIBLE";
    system("rm -rf /data/data/com.pubg.imobile/file");
    system("rm -rf /storage/emulated/0/Download/Telegram/y");
    return env ->NewStringUTF(a.c_str());
}

**Comment by topjohnwu** [comment]
This has nothing to do with `libsu`
