### ISSUE TITLE
Shell.cmd not working on Virtual Machine Apps

### ISSUE THREAD

**Issue by MikaCybertron** [topjohnwu/libsu#115]
```diff
Shell.Result shellResult = Shell.cmd("your command").exec();
```

code doesn't work on Virtual Machine App like VMOS, because it always fails when executing commands, please fix it!

**Comment by MikaCybertron** [comment]
libsu v3.2.1 with ```Shell.Result shellResult = Shell.su("your command").exec();``` work fine in VM App, please fix the newest version!!

**Comment by topjohnwu** [comment]
You provide absolutely no logs, I cannot help you

**Comment by MikaCybertron** [comment]
> You provide absolutely no logs, I cannot help you

nah bro, i can't get the logs about it because i'm using VM Apps, the issue is that i can't execute any command with ```Shell.cmd``` its like it got blocked or something like that which make it fails in VM App, i think you can try and test it by yourself bro with VMOS App to see the issue, because there is no way to get the logs about that code using VM App.

but in version 3.2.1 it work with old code ```Shell.su```
