### ISSUE TITLE
Can we use it on virtuals like parallel space?

### ISSUE THREAD

**Issue by RevealedSoulEven** [topjohnwu/libsu#116]
I know it's such a weired question to be asked... But...

Like we can use it on virtual environments like VMOS and VPhoneGaga but I want to use it on virtuals like Parallel space and all. As Game Guardian supports those virtuals.

But can I use this on virtual? As my app is losing advantage to support those virtuals.

**Comment by MikaCybertron** [comment]
yes it can be used any VM App like VMOS and SandBox, but idk about Parallel space, and also the current version has the issue with executing command with code ```Shell.cmd```, and i hope they will fix the issue

![image](https://user-images.githubusercontent.com/45533977/163383825-c82dd197-90ec-4743-89c8-d8018126bba2.png)

**Comment by RevealedSoulEven** [comment]
Pro mika. I know you are from platinmods team and I had conversation with you on Instagram if you remember.

Btw I was searching for way so that my app could support virtual☹️
