### ISSUE TITLE
How to make the removing of SuFile more secure?

### ISSUE THREAD

**Issue by JagarYousef** [topjohnwu/libsu#117]
**The problem:** 
Using some tools like `Game Guardians` users are able to follow the process ram and find files that have been deleted after the execution then using its physical address they can recover it.

**What I tried:** 
I found it is using [ `rm` ](https://github.com/topjohnwu/libsu/blob/bceab53c9dc543f52a1ff1251b053844aa7d6180/io/src/main/java/com/topjohnwu/superuser/io/SuFile.java#L161) after executing the file to remove it, so I tried to use `shred` instead but it was not useful since `shred` is not effective for some cache partitions (I do not know if it applies to the apps' cache folders in Android).

So my question is: is it possible to make it more secure while removing the file?

**Comment by topjohnwu** [comment]
There is no command that can remove files that is loaded into memory; that is how Linux works

**Comment by JagarYousef** [comment]
> There is no command that can remove files that is loaded into memory; that is how Linux works

So there is no possibility to run the shell's string directly without the need to write it to a file and then remove it after executing?
