### ISSUE TITLE
Unknown issue of modify a file in root, and app can't access that file.

### ISSUE THREAD

**Issue by Yumeryu** [topjohnwu/libsu#12]
Hi 

Goal is to modify an Xml file in root. For this test, I didn't change any Xml file content at all, just read by stream and write by stream. So. 

When I use  SuFileOutputStream and then "ShellUtils.pump" or use OutputStreamWriter(SuFileOutputStream) to write the original file content back to an Xml file. 

Writing file content is successful, but after the Xml file rewritten, original App which need to access that Xml file has lost it's ability to do so. Is there any obvious reason why?

Workaround I found is using "Shell.Sync.sh( list,"cp -r src des")" copy the Xml file out of root to SDCard, and then modify, then using same command to copy file back to root. This way the app can still access this Xml file. However, I've read command cp is not widely supported by phones, does libsu library solved this problem? Is this command safe to use for all phones?

A few tests I did. 

First thought was permission blocked the app to access that Xml file, so I set that Xml file permission to rw-rw-rw-, even rwxrwxrwx, but the app still can't read that rewritten Xml file. 

I can't use RandomAccessFile to modify part of file without rewriting, because this doesn't use stream, so can't get root permission.

I use EsExplorer to check what changes happened to the file after rewritten. 

Original file permission, rw-rw----, after rewritten is rw-r--r--, libsu library doesn't have functions to change permissions separately, so I used EsExplorer to change the permission back to rw-rw----, still no luck. 

Original file Owner is blank, Group is blank. After rewritten, Owner is root, Group is root. libsu library and EsExplorer both don't have anyway to change those back to blank. So I couldn't test this.

Any help is appreciated, thanks a lot.

**Comment by vijai1996** [comment]
I'm not in any way part of this library development but, I can put in my views.

First, is it possible that the direct modification has changed the owner and group or the file permissions? Each app has their user and group for sandboxing. If the group or owner is changed, its inaccessible by the original app anymore.

For `cp` I would assume it is safe because the library includes busybox by default unless you exclude it explicitly while building the app with this library included and busybox does contain cp.

**Comment by topjohnwu** [comment]
@Yumeryu thanks for your report. The issue should be fixed since 1.3.0 release, can you update the library and check it out?
