### ISSUE TITLE
Unable to get background running information

### ISSUE THREAD

**Issue by cxf-boluo** [topjohnwu/libsu#124]
When I use ADB shell to run in the background with fs &  I get the following information
![image](https://user-images.githubusercontent.com/86091961/170835310-6f02fe96-3e33-472a-80c0-2f6db5baf7f5.png)
 
I get empty if I write it like this,  Attempting asynchrony is also null [ ]
![image](https://user-images.githubusercontent.com/86091961/170835480-cc200325-f9d9-410e-9d17-5047696a2d4a.png)

**Comment by topjohnwu** [comment]
Sorry, but I cannot understand what you're trying to describe
