### ISSUE TITLE
The jni layer cannot get su correctly

### ISSUE THREAD

**Issue by J-iang-wan** [topjohnwu/libsu#128]
Hello, I used your project and loaded the imgui floating window (also an open source project), I used egl to create the canvas, my jni got root permissions, but I replaced the floating window with my own service After startup, the jni layer has no root privileges, how can I solve it or have your contact information, I can take a screenshot of my code snippet to you

**Comment by Bitm-m** [comment]
解决了吗

**Comment by hashqueue** [comment]
> 解决了吗

试试这个[https://github.com/RikkaApps/Shizuku](https://github.com/RikkaApps/Shizuku)

**Comment by topjohnwu** [comment]
The root service is not running in the same process as your application. Also, I cannot understand what we are trying to achieve here.
