### ISSUE TITLE
SuFile.isDirectory() can throw NoShellException (and shouldn't)

### ISSUE THREAD

**Issue by Fox2Code** [topjohnwu/libsu#131]
Due to `SuFile.isDirectory()` call `SuFile.cmdBool()` call `SuFile.getShell()` call `Shell.getShell()` call `MainShell.get()` call `BuilderImpl.build()` that can throw `NoShellException` and can causes crashes as it is a common assumption that `File.isDirectory()` does not throw any errors.

This is very obscure effect was discovered by someone using my app that use libsu.

**Comment by vvb2060** [comment]
I think this is expected behavior and it is the developer's responsibility to check that the shell is valid before using it.

**Comment by Fox2Code** [comment]
I personally disagree that `isDirectory()` should throw `NoShellException` because `SuFile` extends `File`, when this issue crashed my app on someone device, I had no idea and it was a existing behavior for me, so this was very unexpected for me.

I already did my best do avoid calling `SuFile` when root does not exists or is not available, and this "behavior" was really unexpected, so I think it's definitely a flaw of the library because the goal of a library is to help developers make programs.

But this is mainly a mater of opinion, so I understand the disagreement.

**Comment by topjohnwu** [comment]
Well, `SuFile` is backed by a shell; if you have no shell available, how does it operate? If you are really concerned about this, you should move over to use the `nio` module.

**Comment by Fox2Code** [comment]
Well, I reported this because `SuFile` crashed despite my app checking for root access.
