### ISSUE TITLE
Missing Proguard / R8 Config causes crashes

### ISSUE THREAD

**Issue by Nek-12** [topjohnwu/libsu#134]
Running a release build with R8 enabled causes the following warnings to be issued:

```
Missing class com.topjohnwu.superuser.Shell$Job (referenced from: java.lang.Object com.kevlar.rooting.detection.status.SelinuxDetectorKt$detectSelinux$2.invokeSuspend(java.lang.Object) and 9 other contexts)
Missing class com.topjohnwu.superuser.Shell$Result (referenced from: com.topjohnwu.superuser.Shell$Result com.kevlar.rooting.shell.dump.BinaryDump.invocationResult and 17 other contexts)
Missing class com.topjohnwu.superuser.Shell (referenced from: java.lang.Object com.kevlar.rooting.detection.status.SelinuxDetectorKt$detectSelinux$2.invokeSuspend(java.lang.Object) and 9 other contexts)
```
Unsurprisingly, R8-minified Android app using the library crashes with ClassNotFoundException.

This is an issue discovered when using [Kevlar](https://github.com/kevlar-kt/kevlar) but I believe should be addressed here.

Similar issue #41 has been closed as #wontfix without much discussion or consideration, I think this one is a consequence.

UPD:
Upon some investigation, I believe the reason for proguard rules not being applied is the usage of `proguard-rules.pro` and not `consumer-rules.pro`

P.S. I'm using R8.fullMode = true

**Comment by vvb2060** [comment]
I'm pretty sure these R8 warnings are not our problem.

**Comment by Nek-12** [comment]
Well  making sure files that are not referenced in code are not stripped from the library is the responsibility of the library. Each library defines its own proguard files.

**Comment by vvb2060** [comment]
Are you an Android developer?

**Comment by Nek-12** [comment]
As my profile states, yes I am.

**Comment by Nek-12** [comment]
@topjohnwu when will this be addressed?

**Comment by topjohnwu** [comment]
The included proguard file in the library should be sufficient

**Comment by Nek-12** [comment]
But as the issue description states it is not sufficient, I am unable to build my project without workarounds. Can this be reopened please?
