### ISSUE TITLE
"No such file or directory" when opening file through shell

### ISSUE THREAD

**Issue by reveny** [topjohnwu/libsu#146]
I'm trying to read file information through a shell command with the following code:

`Shell.cmd("file /data/data/com.package.name/files/test.txt").exec();`
As a result I get
`/data/data/com.package.name/files/test.txt: cannot open: No such file or directory`

When I run the same command through ADB or through Termux I get the wanted result but with Shell.cmd in my app I do not get any result. The file definitely exists in the wanted location.

I also added the following permissions to my app but still no result.
`<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`

**Comment by DDeveloper16** [comment]
Facing this issue as well.

**Comment by XayahSuSuSu** [comment]
**FLAG_MOUNT_MASTER** needed.
```
Shell.Builder.create().setFlags(Shell.FLAG_MOUNT_MASTER or Shell.FLAG_REDIRECT_STDERR)
```

**Comment by reveny** [comment]
> **FLAG_MOUNT_MASTER** needed.
> 
> ```
> Shell.Builder.create().setFlags(Shell.FLAG_MOUNT_MASTER or Shell.FLAG_REDIRECT_STDERR)
> ```

Works. Thank you
