### ISSUE TITLE
使用360加固后无法绑定RootService

### ISSUE THREAD

**Issue by chejfj** [topjohnwu/libsu#160]
如题，刚开始我以为是混淆规则不到位，重新调整了混淆规则，然后再次使用360加固，结果还是一样的。只要使用了加固，RootService就不能成功绑定

**Comment by MIkeeJY** [comment]
建议用字节码混淆，别用加固了~加固的兼容性不好

**Comment by chejfj** [comment]
> 建议用字节码混淆，别用加固了~加固的兼容性不好

是的，我也这么觉得。我改用了加密方式

**Comment by 3365427906** [comment]
你好，我想问一下我刷新构建后重新打包安装后绑定Rootservice失败，请问一下这是什么原因呢

**Comment by chejfj** [comment]
> 你好，我想问一下我刷新构建后重新打包安装后绑定Rootservice失败，请问一下这是什么原因呢

应该是混淆原因

**Comment by 3365427906** [comment]
> > 你好，我想问一下我刷新构建后重新打包安装后绑定Rootservice失败，请问一下这是什么原因呢
> 
> 应该是混淆原因

可是我使用Android studio打包的，没有启用混淆，目前还没解决问题，您能帮我看看吗

**Comment by topjohnwu** [comment]
加固可能把 classloader 給改了，這樣沒辦法支援

**Comment by jing1007209484** [comment]
有解决的嘛？？？

**Comment by sweord** [comment]
无解
