### ISSUE TITLE
Doesn't support targetSdk>31?

### ISSUE THREAD

**Issue by chillsoul** [topjohnwu/libsu#164]
Here is my code:
```
package com.example.fragwatcher;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import androidx.appcompat.app.AppCompatActivity;
import com.topjohnwu.superuser.Shell;
import java.util.List;

public class MainActivity extends AppCompatActivity implements View.OnClickListener{
    
    static {
        // Set settings before the main shell can be created
        Shell.enableVerboseLogging = BuildConfig.DEBUG;
        Shell.setDefaultBuilder(Shell.Builder.create()
                .setFlags(Shell.FLAG_REDIRECT_STDERR)
                .setTimeout(10)
        );
    }
    Button startButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        startButton=findViewById(R.id.button);
        startButton.setOnClickListener(this);

    }
    @Override
    public void onClick(View v){
        Shell.Result result;
        // Execute commands synchronously
        result = Shell.cmd("ls").exec();
        List<String> out = result.getOut();  // stdout
        System.out.println(out);
    }
}
```
At first, there are always 

> 2023-10-05 10:38:55.541 27292-27292 BUILDER                 com.example.myapp              D  exec su
> 2023-10-05 10:38:55.557 27292-27292 LIBSU                   com.example.myapp              D  java.io.IOException: Cannot run program "su": error=13, Permission denied

then i try to change `targetSdk` in build.gradle, and i found when it changes to lower than 32 (e.g. 31), this error will disappear,but if it changes to 32 or upper, permission will be denied again.

Android Studio Emulator Pixel 5 API 34
compileSdk is 33, default setting in android studio empty java project.

**Comment by hosein-nadali** [comment]
same problem. any solution? @topjohnwu

**Comment by chillsoul** [comment]
> same problem. any solution? @topjohnwu

for your reference, i set  targetsdk to 31

**Comment by hosein-nadali** [comment]
> same problem. any solution? @topjohnwu

I have to change compileSdk too?
I changed targetSdk but still have problem

**Comment by chillsoul** [comment]
> compileSdk is 33

my compileSdk is 33

**Comment by hosein-nadali** [comment]
> > compileSdk is 33
> 
> my compileSdk is 33

It's not for targetSdk. i think google reduced user access on this topic for androidSdk > 26.
maybe we need add a permission or something like this. 

I tested on androidSdk 26 with targetSdkVersion 33 and it's worked

**Comment by topjohnwu** [comment]
You need to run the emulator with Magisk root. The default `su` binary cannot be used by normal apps
