### ISSUE TITLE
LIBSU: java.io.InterruptedIOException

### ISSUE THREAD

**Issue by tumatanquang** [topjohnwu/libsu#165]
I am writing an application to stop some packages running, but I have encountered an error:
```
D/LIBSU: java.io.InterruptedIOException
        at com.topjohnwu.superuser.internal.JobImpl.run(JobImpl.java:79)
        at com.topjohnwu.superuser.internal.ShellImpl.execTask(ShellImpl.java:230)
        at com.topjohnwu.superuser.internal.JobImpl.exec0(JobImpl.java:100)
        at com.topjohnwu.superuser.internal.JobImpl.lambda$submit$0$com-topjohnwu-superuser-internal-JobImpl(JobImpl.java:132)
        at com.topjohnwu.superuser.internal.JobImpl$$ExternalSyntheticLambda0.run(Unknown Source:6)
        at com.topjohnwu.superuser.internal.SerialExecutorService.call(SerialExecutorService.java:51)
        at com.topjohnwu.superuser.internal.SerialExecutorService.call(SerialExecutorService.java:34)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.lang.InterruptedException
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:418)
        at java.util.concurrent.FutureTask.get(FutureTask.java:190)
        at com.topjohnwu.superuser.internal.JobImpl.run(JobImpl.java:76)
        at com.topjohnwu.superuser.internal.ShellImpl.execTask(ShellImpl.java:230) 
        at com.topjohnwu.superuser.internal.JobImpl.exec0(JobImpl.java:100) 
        at com.topjohnwu.superuser.internal.JobImpl.lambda$submit$0$com-topjohnwu-superuser-internal-JobImpl(JobImpl.java:132) 
        at com.topjohnwu.superuser.internal.JobImpl$$ExternalSyntheticLambda0.run(Unknown Source:6) 
        at com.topjohnwu.superuser.internal.SerialExecutorService.call(SerialExecutorService.java:51) 
        at com.topjohnwu.superuser.internal.SerialExecutorService.call(SerialExecutorService.java:34) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
        at java.lang.Thread.run(Thread.java:1012) 
```

This is my code:
```
forceStopButton.setOnClickListener(v->{
	List<ApplicationInfo> checkedPackages = appListAdapter.getCheckedPackages();
	forceStopTask = new ForceStopPackagesTask(this).execute(checkedPackages);
	if(!checkedPackages.isEmpty()) {
		boolean isCheckedAll = checkBoxSelectAll.isChecked();
		for(ApplicationInfo checkedPackage : checkedPackages) {
			String packageName = checkedPackage.packageName;
			if(!forceStopWhitelistPackages.contains(packageName)) {
				Shell.cmd("am force-stop " + packageName).submit();
			}
			if(!isCheckedAll) {
				appListAdapter.remove(checkedPackage);
			}
		}
		if(isCheckedAll) {
			appListAdapter.removeAll();
		}
		appListAdapter.notifyDataSetChanged();
		Toast.makeText(this, R.string.force_stop_app_success_notif, Toast.LENGTH_SHORT).show();
		if(appListAdapter.isEmpty()) {
			checkBoxSelectAll.setChecked(false);
			AlertDialog.Builder reloadRunningAppConfirm = new AlertDialog.Builder(this);
			reloadRunningAppConfirm
					.setTitle(R.string.reload_running_apps_title)
					.setMessage(R.string.reload_running_apps_message)
					.setPositiveButton(R.string.confirm_button, (dialog, id)->{
						if(collectTask != null && !collectTask.isCancelled()) {
							collectTask.cancel(false);
							collectTask = null;
						}
						collectTask = new CollectRunningPackagesTask(this).execute();
					})
					.setNegativeButton(R.string.cancel_button, (dialog, id)->Toast.makeText(this, R.string.action_cancelled_notif, Toast.LENGTH_SHORT).show())
					.create()
					.show();
		}
	}
	else {
		Toast.makeText(this, R.string.no_app_selected_error, Toast.LENGTH_SHORT).show();
	}
});
```
I tried to replace between `submit()` and `exec()` but still had that problem.
The version I use is 5.2.1.

**Comment by sprzemyslaw** [comment]
> I am writing an application to stop some packages running, but I have encountered an error:
> ```
> D/LIBSU: java.io.InterruptedIOException
>         at com.topjohnwu.superuser.internal.JobImpl.run(JobImpl.java:79)
>         at com.topjohnwu.superuser.internal.ShellImpl.execTask(ShellImpl.java:230)
>         at com.topjohnwu.superuser.internal.JobImpl.exec0(JobImpl.java:100)
>         at com.topjohnwu.superuser.internal.JobImpl.lambda$submit$0$com-topjohnwu-superuser-internal-JobImpl(JobImpl.java:132)
>         at com.topjohnwu.superuser.internal.JobImpl$$ExternalSyntheticLambda0.run(Unknown Source:6)
>         at com.topjohnwu.superuser.internal.SerialExecutorService.call(SerialExecutorService.java:51)
>         at com.topjohnwu.superuser.internal.SerialExecutorService.call(SerialExecutorService.java:34)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
>         at java.lang.Thread.run(Thread.java:1012)
>      Caused by: java.lang.InterruptedException
>         at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:418)
>         at java.util.concurrent.FutureTask.get(FutureTask.java:190)
>         at com.topjohnwu.superuser.internal.JobImpl.run(JobImpl.java:76)
>         at com.topjohnwu.superuser.internal.ShellImpl.execTask(ShellImpl.java:230) 
>         at com.topjohnwu.superuser.internal.JobImpl.exec0(JobImpl.java:100) 
>         at com.topjohnwu.superuser.internal.JobImpl.lambda$submit$0$com-topjohnwu-superuser-internal-JobImpl(JobImpl.java:132) 
>         at com.topjohnwu.superuser.internal.JobImpl$$ExternalSyntheticLambda0.run(Unknown Source:6) 
>         at com.topjohnwu.superuser.internal.SerialExecutorService.call(SerialExecutorService.java:51) 
>         at com.topjohnwu.superuser.internal.SerialExecutorService.call(SerialExecutorService.java:34) 
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
>         at java.lang.Thread.run(Thread.java:1012) 
> ```
> 
> This is my code:
> ```
> forceStopButton.setOnClickListener(v->{
> 	List<ApplicationInfo> checkedPackages = appListAdapter.getCheckedPackages();
> 	forceStopTask = new ForceStopPackagesTask(this).execute(checkedPackages);*/
> 	if(!checkedPackages.isEmpty()) {
> 		boolean isCheckedAll = checkBoxSelectAll.isChecked();
> 		for(ApplicationInfo checkedPackage : checkedPackages) {
> 			String packageName = checkedPackage.packageName;
> 			if(!forceStopWhitelistPackages.contains(packageName)) {
> 				Shell.cmd("am force-stop " + packageName).submit();
> 			}
> 			if(!isCheckedAll) {
> 				appListAdapter.remove(checkedPackage);
> 			}
> 		}
> 		if(isCheckedAll) {
> 			appListAdapter.removeAll();
> 		}
> 		appListAdapter.notifyDataSetChanged();
> 		Toast.makeText(this, R.string.force_stop_app_success_notif, Toast.LENGTH_SHORT).show();
> 		if(appListAdapter.isEmpty()) {
> 			checkBoxSelectAll.setChecked(false);
> 			AlertDialog.Builder reloadRunningAppConfirm = new AlertDialog.Builder(this);
> 			reloadRunningAppConfirm
> 					.setTitle(R.string.reload_running_apps_title)
> 					.setMessage(R.string.reload_running_apps_message)
> 					.setPositiveButton(R.string.confirm_button, (dialog, id)->{
> 						if(collectTask != null && !collectTask.isCancelled()) {
> 							collectTask.cancel(false);
> 							collectTask = null;
> 						}
> 						collectTask = new CollectRunningPackagesTask(this).execute();
> 					})
> 					.setNegativeButton(R.string.cancel_button, (dialog, id)->Toast.makeText(this, R.string.action_cancelled_notif, Toast.LENGTH_SHORT).show())
> 					.create()
> 					.show();
> 		}
> 	}
> 	else {
> 		Toast.makeText(this, R.string.no_app_selected_error, Toast.LENGTH_SHORT).show();
> 	}
> });
> ```
> I tried to replace between `submit()` and `exec()` but still had that problem.
> The version I use is 5.2.1.

**Comment by topjohnwu** [comment]
The new internal task scheduling should solve this issue
