### ISSUE TITLE
LIBRARY REFUSES to access files. 

### ISSUE THREAD

**Issue by rom4ster** [topjohnwu/libsu#170]
So if I were to do an ls on an apps  private directory from a normal root shell it works just fine. But no matter what I do here, I get file not found. Weather its through Shell.getShell { //code ...}  or Shell.cmd("ls or cp or whatever command"). I even tried moving it into a script and running that. NOTHING.

Somehow tasker is able to run these things so I am wondering what is wrong. 

Here is the setup code in MainActivity

```

    companion object {

        init {
            runAsRoot("ls")
            Shell.enableVerboseLogging = true
            Shell.setDefaultBuilder(
                Shell.Builder.create()
                    .setFlags(Shell.FLAG_REDIRECT_STDERR)
                    .setTimeout(10)
            )
        }

    }


```

**Comment by buttercookie42** [comment]
I wonder whether that's in any way related to https://github.com/topjohnwu/libsu/issues/75, i.e. whether also passing `FLAG_MOUNT_MASTER` resolves the issue?

**Comment by rom4ster** [comment]
Yep forgot to update this lol, Yes. YOU NEED FLAG MOUNT MASTER.
