### ISSUE TITLE
Worst Documentation

### ISSUE THREAD

**Issue by invincible003** [topjohnwu/libsu#184]
This is the probably the worst document I have ever seen , no any good working examples on remote file system I dont understand why just to get some credit people put others life in problems .

**Comment by Arian04** [comment]
the javadocs are good. if you don't understand them, that's only due to your own incompetence, not the library developer's skills.

https://topjohnwu.github.io/libsu/com/topjohnwu/superuser/nio/FileSystemManager.html#getRemote(IBinder)
