### ISSUE TITLE
Checking for root

### ISSUE THREAD

**Issue by gurupras** [topjohnwu/libsu#20]
I'm writing an app that wants to make use of root if it is available. The way Android runtime permissions were designed was to allow app developers to explain how they use a permission before requesting it.

Currently, the only way I can get the su permission grant dialog to show up is to try and _use_ root privileges. Is there a way to _test_ whether root access is available before _using_ (implicitly triggering check) it.

I'm struggling with coming up with a way to:

1. Check if root is available
2. Show dialog explaining how app uses root
3. Trigger root app's grant/deny dialog

**Comment by victorlapin** [comment]
Shell.isRootAvailable()

**Comment by victorlapin** [comment]
Understand though, that the only way to check for root is to try to get su access, it's not a proper runtime permission

**Comment by gurupras** [comment]
I see a `Shell.rootAvailable()`, is this what you're referring to? Also, just for clarification, does this check whether the device has root or whether the app has root privileges?

**Comment by topjohnwu** [comment]
@gurupras when you use `Shell.rootAccess()`, it will actually request a root shell (execute `su`), and cache the result in the container. Unfortunately, there is no way to know whether root is available until you actually request for it.
You **can** check the availability of the `su` command, but there is no way to know whether it actually works or not (e.g. user denies root access by default)

**Comment by j3ptk87** [comment]
To all of the great minds giving knowledge to any who seek it freely I say You Are The Truth which shall FREE us all.

**Comment by smichel17** [comment]
> You can check the availability of the su command

As I understand it, the way to do this would be to open a non-root shell and then run `command -v su` or similar? Would you consider adding a utility function to avoid this boilerplate? Something like `boolean deviceIsLikelyRooted()`.

The main use case is communicating to users of non-rooted devices that certain functionality will not work, without throwing up an unnecessary permission request on rooted devices (it irritates me when apps do this; I don't want to grant permissions until they're needed for something). No fancy tricks — I am not looking to detect root functionality if the user wants to hide it from me :)

**Comment by Bob8259** [comment]
in 2025, versioin 6.0.0, you can use the following method to check root permission
```
  Shell.getShell { shell: Shell? ->
            if (shell != null && shell.isRoot) {
                // has root permission
                hasRootAccess = true
                checkAndRequestPermission()
            }else{
                //write your logic here
            }
        }
```
