### ISSUE TITLE
Realtime massive shell output reading

### ISSUE THREAD

**Issue by fkeglevich** [topjohnwu/libsu#21]
Hi,
I'm the author of Raw Dumper (camera app for taking raw pictures on x86 phones, like the Zenfone 2)
and I'm planning to replace libsuperuser with libsu.

I have a really specific use case: during the app lifetime, I need to keep parsing the massive output of a system-level logcat command; in realtime, without allocating String objects.

Overriding the Task interface and calling execTask would suit my needs?

PS: The whole logcat reading stuff is needed to get some raw sensor AWB gains to generate raw pics with pretty colors and proper white balance.

**Comment by topjohnwu** [comment]
@fkeglevich sorry for the extremely late reply.
Yes, that interface is designed to be used to directly interact with raw STDIN/STDOUT/STDERR.
