### ISSUE TITLE
Cannot read pseudo-files with IO

### ISSUE THREAD

**Issue by gurupras** [topjohnwu/libsu#22]
The IO library does not work for pseudo-files.

Here's normal non-root Java code that works:
```
> FileUtils.readFileToString(new File("/proc/cpuinfo"))
Processor	: AArch64 Processor rev 2 (aarch64)
processor	: 0
BogoMIPS	: 38.00
...
```
However, when you try to do the same with libsu's IO library, it always returns empty.
The example file chosen here (`/proc/cpuinfo`) doesn't even need root privileges.

I'm not too familiar with Java. However, If you can point me to the faulty code, I can take a shot at fixing it.

**Comment by topjohnwu** [comment]
It is a limitation of using shell for I/O. In my implementation it has to get the file size before it could to I/O, and for character files the size is always 0 (as returned from `stat`). A workaround is using `Shell.su("cat /path/to/file").exec().getOutput()` to get the content of the whole file.

**Comment by victorlapin** [comment]
So that's why my checks for the recovery script file size always fail... Thanks TJW
