### ISSUE TITLE
ProcessImpl.exitValue() can take a lot of time to complete

### ISSUE THREAD

**Issue by MPeti1** [topjohnwu/libsu#26]
If I want to list a big folders's files (~14k files), most of the time goes by creating the (unused) stack trace for an exception which is just used for returning a true if occurred. 
https://github.com/topjohnwu/libsu/blob/1041886aef705f1ff328d08223e52acc2c72b2b4/superuser/src/main/java/com/topjohnwu/superuser/internal/ShellImpl.java#L169

If the process is still running while executing ProcessImpl.exitValue() (and most of the times it does), `java.lang.Throwable.nativeFillInStackTrace` can take from 1,5 ms to 66,7 ms. In a loop of 14k files, this way of checking if the shell process vanished wastes ~80% of the time after we got the response.

ProcessImpl.isAlive() is not supported below SDK 26, but ProcessImpl.exitValue can still be checked via reflection. You could first check if that field exists (since there could be roms which don't have it), and if not, you could still use the old approach, and from SDK 26 you could use isAlive()

**Comment by topjohnwu** [comment]
Thanks for the suggestion! It seems that on Java 8 we can use `boolean UNIXProcess.hasExit`, and on Java 7 we can use `Integer ProcessImpl.exitValue == null`. This shall cover most cases.
I will add it to `libsu` soon!

**Comment by MPeti1** [comment]
Yesterday I started testing it on an SDK 23 device (although it's a miui dev rom from ~1,5 years ago), and then that's why it wasn't able to find the ProcessImpl class :D could I ask where did you found the UnixProcess class?

**Comment by topjohnwu** [comment]
libcore in AOSP. Java 8 is introduced in SDK 23, and that is the version with the new implementation

**Comment by MPeti1** [comment]
There seems to be a problem. For some reason `Class.forName("java.lang.UNIXProcess")` throws ClassNotFoundException, and even for `java.lang.ProcessImpl`. Are you sure UNIXProcess is added in SDK 23?

![kep](https://user-images.githubusercontent.com/9215491/48362285-96459380-e6a3-11e8-8947-99a46e31fa5e.png)

**Comment by MPeti1** [comment]
I found that Class.forName() doesn't accept `.` in between class and inner class name, and then the class string should be `java.lang.ProcessManager$ProcessImpl`. Even the debug menu marks it clearly after the variable name, and the variable shadowKlass in each of them..
But still, it seems MIUI (and maybe other) roms which are built based on SDK23 don't have UNIXProcess class

**Comment by topjohnwu** [comment]
@MPeti1 I'm not finding direct class names, I get the class from the return object

**Comment by MPeti1** [comment]
Yes, I've seen the changes :)
