### ISSUE TITLE
Executing scripts with exit or return code

### ISSUE THREAD

**Issue by bluecatpixel** [topjohnwu/libsu#28]
Hi @topjohnwu.

Great job and thanks for your work!

I tried the lib but while executing line commands everything is working fine when I try to execute scripts I found that the script never executes.

I was able to find that the problem is in the exit. Whenever I use exit (also in commands) the lib always returns code -1. I tried to substitute the exit by return but I always get the code -1.

I tried a sync call:
> Shell.Result result = Shell.su(getResources().openRawResource(resId)).exec();
> mTvCode.setText("Code: " + result.getCode());
> List<String> out = result.getOut();
> StringBuilder sbOut = new StringBuilder();
> if (out != null) {
> &nbsp;&nbsp;&nbsp;&nbsp;for (String o : out) {
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sbOut.append(o);
> &nbsp;&nbsp;&nbsp;&nbsp;}
> }
> mTvOutput.setText("Out: " + sbOut.toString());
> List<String> err = result.getErr();
> StringBuilder sbErr = new StringBuilder();
> if (err != null) {
> &nbsp;&nbsp;&nbsp;&nbsp;for (String e : err) {
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sbErr.append(e);
> &nbsp;&nbsp;&nbsp;&nbsp;}
> }
> mTvErr.setText("Err: " + sbErr.toString());

And I tried async call:
> Shell.su(getResources().openRawResource(R.raw.script))
> &nbsp;&nbsp;&nbsp;&nbsp;.to(consoleList)
> &nbsp;&nbsp;&nbsp;&nbsp;.submit(result -> {
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mTvCode.setText("Code: " + result.getCode());
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;List<String> out = result.getOut();
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;StringBuilder sbOut = new StringBuilder();
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (out != null) {
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for (String o : out) {
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sbOut.append(o);
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mTvOutput.setText("Out: " + sbOut.toString());
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;List<String> err = result.getErr();
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;StringBuilder sbErr = new StringBuilder();
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (err != null) {
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for (String e : err) {
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sbErr.append(e);
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mTvErr.setText("Err: " + sbErr.toString());
> &nbsp;&nbsp;&nbsp;&nbsp;});

The result is always the same.

Here's one script example:
> #!/system/bin/sh
> function exit_error(){
> &nbsp;&nbsp;&nbsp;&nbsp;case "$1" in
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1)
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;echo 'busybox is not installed'
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;;
> &nbsp;&nbsp;&nbsp;&nbsp;esac
> &nbsp;&nbsp;&nbsp;&nbsp;#exit 2
> &nbsp;&nbsp;&nbsp;&nbsp;return 2
> }
> 
> busybox > /dev/null || exit_error 1
> 
> if [[ ! -f /sdcard/file.txt ]]; then
> &nbsp;&nbsp;&nbsp;&nbsp;echo 'File not exists'
> &nbsp;&nbsp;&nbsp;&nbsp;#exit 1
> &nbsp;&nbsp;&nbsp;&nbsp;return 1
> fi
> 
> echo 'Exiting'
> #exit 0
> return 0`

Am I doing something wrong or is this a limitation?

Thanks in advance.
JS

**Comment by topjohnwu** [comment]
You should never terminate the shell!  The shell in libsu is a long living session, exiting will terminate the process, and thus it cannot retrieve the return code.
You can run that code in a subshell, e.g. `(shell_script)` or `sh shell_script`, which will fork another process from the shell, and exiting will only terminate the subshell but not the shell used in `libsu`
