### ISSUE TITLE
Read output/error as a stream?

### ISSUE THREAD

**Issue by Mygod** [topjohnwu/libsu#29]
This could be helpful to prevent OOMs in situations like copying a large file or reading logcat.

EDIT: By the way, my Crashlytics indeed caught OOMs when my code was attempting to save logcat to a file.

**Comment by topjohnwu** [comment]
@Mygod please provide more specific reports, I don't know what is your issue.

**Comment by Mygod** [comment]
Currently, it seems like the output and error stream is returned via `List<String>`. It would be great if you can access them as `InputStream` (possibly wrapped to handle EOFs).

**Comment by topjohnwu** [comment]
@Mygod there are `SuFileInputStream`, `SuFileOutputStream` to use. There is also the raw `Shell.execTask()` to use. Please read the Javadoc for more information.

**Comment by forntoh** [comment]
@topjohnwu How do we use `Shell.execTask()` I want the output as bytes array not list of string

I tried 

```kotlin
Shell.getShell().execTask { stdin, stdout, _ ->
    stdin.write("mycmd -p\n".toByteArray())
    stdin.flush()
    val bytes = stdout.readBytes()  // <--- It doesn't reach here
    ...
}
```

But it doesn't reach the line with `stdout.readBytes()`
