### ISSUE TITLE
cant hide root detection

### ISSUE THREAD

**Issue by idnfrz89** [topjohnwu/libsu#3]
hi mr topjohnwu,
there is some apps still can launched but its should not detecting root. can help me to add this apk to libsu? i already using magisk hide but its still detecting root.

here I attach the application name 
1. com.gojek.driver.car or gocar driver.apk
2. com.gojek.driver.bike or gojek driver.apk
3. com.grabtaxi.driver2 or grab driver.apk
this app its same as com.ubercab.driver.
I using mi tissot with pass safetynet.

![screenshot_2018-03-03-15-25-06-083_com topjohnwu magisk](https://user-images.githubusercontent.com/37012574/36932140-788d3d08-1ef7-11e8-8b70-e365eec4c680.png)
![screenshot_2018-03-03-15-25-22-336_com topjohnwu magisk](https://user-images.githubusercontent.com/37012574/36932141-78bd5830-1ef7-11e8-9b9d-bdcd8c334eb6.png)
![screenshot_2018-03-03-15-25-39-215_com topjohnwu magisk](https://user-images.githubusercontent.com/37012574/36932142-78f28406-1ef7-11e8-8b70-a45d8570d655.png)

thanks before mr.topjohnwu.

**Comment by topjohnwu** [comment]
This place is not a place to report Magisk issues
