### ISSUE TITLE
libsu 2.3.0 no longer seems to support Android 6.0.1

### ISSUE THREAD

**Issue by fiatCurrency** [topjohnwu/libsu#32]
Trying to build a project in AS with a dependency on libsu 2.3.0, I get errors relating to 'common invoke' and 'static methods in interfaces', which are apparently only available in SDK 26+. Samsung haven't upgraded their stock since 6.0.1 for me, which means I'm stuck at SDK 23, so can't go beyond libsu 2.2.0
Any chance of removing these weird Java/SDK features, or can android M no longer be supported ?

**Comment by topjohnwu** [comment]
Have you enabled Java 8 support? Please check the README, and also the official Android documentation https://developer.android.com/studio/write/java8-support

**Comment by fiatCurrency** [comment]
Yes, I just found out a few minutes ago. 

I am working on a project which is basically three modules: driver, ui, controls library. Only the first of those depends on libsu, but it seems I have to:

Specify Java 1.8 for _all_ the modules' build.gradle files, even though none of mine are actually using Java 1.8 features. Apparently, just doing it at the top project level build.gradle file isn't enough.

Specify the maven repository in the top level build.gradle file, even though only one module is
using it.

Add a packaging option in _one_ of my modules' build.gradle files, to prevent some .DEX file or other
from being duplicated.

It's getting very complicated trying to work out what goes in each of the modules' build files, and 
what goes into the top level. I will do some pruning tomorrow.

I don't know why AS mentioned Android-N in the error message; it's nothing to do with that; it's the
Java version itself.


It all works properly now. I'll make a donation on Tuesday.

-


Oddly, it all worked without it yesterday, when I was using < 2.3.0


It also appears that you have to put the jitpack.io maven repository in the build.gradle file for the whole project, not just the (one) module that has the dependency on libsu. Is this correct ?

**Comment by topjohnwu** [comment]
I don't know why the Android team has not default to Java 8 yet. There are absolutely no reason to not use Java 8 in all projects. Jake Wharton, a really famous Android developer, now also working for Google in support libraries, Kotlins and stuffs, have force all his libraries to use Java 8 just to push the whole ecosystem forward :)

You can put the `maven { url "https://jitpack.io" }` within the top gradle file under `subprojects` or `allprojects`, or you can add it in a specific module's gradle file.
