### ISSUE TITLE
ANR caused by deadlock in Shell.newInstance

### ISSUE THREAD

**Issue by Mygod** [topjohnwu/libsu#33]
Under the hood of Shell.newInstance, it delegates the creation of new shell instance to the main thread. This could be problematic if the main thread is waiting for it to finish (e.g. using a synchronized/monitor to guard around the root shell). Should this be fixed?

**Comment by topjohnwu** [comment]
It depends on which thread you called Shell.newInstance. That function always returns a shell synchronously. You can check Magisk Manager to see what I was doing there: asynchronously get a shell in splash screen, and launch main activity after we got a shell instance (the instance will be internally cached)

**Comment by Mygod** [comment]
Can you replace it with a simple synchronized block or something so that the thread can be instantiated in any thread instead of main thread only? That would solve my deadlock issue.

**Comment by Mygod** [comment]
Any thoughts? Thank you!
