### ISSUE TITLE
Improvenents with SuFile / IO

### ISSUE THREAD

**Issue by H4xX0r1337** [topjohnwu/libsu#34]
By using your library, I ran into the following issues.
1) SuFile.delete() does not use root to delete files.
2) If issue 1 is fixed, the system partition is still often mounted ro instead of rw, some method of remounting would be nice.

**Comment by topjohnwu** [comment]
1. `SuFile` is now updated to always use shell operations
2. I will not provide methods for simply running a command like this `mount -o rw,remount /system`

**Comment by AndroidDeveloperLB** [comment]
@topjohnwu Is there a Wiki that shows all that's available? Is there, for example, a way to convert apps to system apps and back? Is BusyBox required for it?
