### ISSUE TITLE
Is there a Wiki? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/libsu#36]
Is there a Wiki that shows all that's available? 

Is there, for example, a way to convert apps to system apps and back? Is BusyBox required for it?

**Comment by topjohnwu** [comment]
This library simply provides an easy way for apps to communicate with a root shell with Java/Kotlin. It does not provide any magical features.

For documentation, `README.md`, the example app, and Javadocs are good places to start

**Comment by AndroidDeveloperLB** [comment]
OK where is the link to the Javadocs?
I don't see it. Only in code...

**Comment by topjohnwu** [comment]
There is a icon in the README

**Comment by AndroidDeveloperLB** [comment]
Oh this:
https://jitpack.io/com/github/topjohnwu/libsu/docs/latest/javadoc/

OK sorry about this.
