### ISSUE TITLE
How to "push forward" from inputStream into shell?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/libsu#38]
Hello, 
I'm trying to use this library to install split-APK files, as this one does:

https://github.com/Aefyr/SAI/blob/master/app/src/main/java/com/aefyr/sai/installer/rooted/RootedSAIPackageInstaller.java

More specifically, I'm trying to convert this code of the above, which pushes the file as installation source to the "pm install-write" command :

```
while (apkSource.nextApk())
     ensureCommandSucceeded(Root.exec(String.format("pm install-write -S %d %d \"%s\"", apkSource.getApkLength(), sessionId, apkSource.getApkName()), apkSource.openApkInputStream()));
```

And the code for its root class is probably as such:

```
    private static Result execInternal(String command, @Nullable InputStream inputPipe) {
        try {
            Process process = Runtime.getRuntime().exec(String.format("su -c %s", command));

            StringBuilder stdOutSb = new StringBuilder();
            StringBuilder stdErrSb = new StringBuilder();
            Thread stdOutD = writeStreamToStringBuilder(stdOutSb, process.getInputStream());
            Thread stdErrD = writeStreamToStringBuilder(stdErrSb, process.getErrorStream());

            if (inputPipe != null) {
                IOUtils.copyStream(inputPipe, process.getOutputStream());
                inputPipe.close();
                process.getOutputStream().close();
            }

            process.waitFor();
            stdOutD.join();
            stdErrD.join();

            return new Result(command, process.exitValue(), stdOutSb.toString().trim(), stdErrSb.toString().trim());
        } catch (Exception e) {
            Log.w(TAG, "Unable execute command: ");
            Log.w(TAG, e);
            return new Result(command, -1, "", "Java exception: " + Utils.throwableToString(e));
        }
    }
```

So, what I tried using this library, is this :

```
            for (apkSource in fileInfoList) {
                //                pm install-write -S %d %d \"%s\"", apkSource.getApkLength(), sessionId, apkSource.getApkName()), apkSource.openApkInputStream()));
                val filePath = File(apkSource.parentFilePath, apkSource.fileName).absolutePath
                val result = Shell.su("\"pm install-write -S ${apkSource.fileSize} $sessionId \"${apkSource.fileName}\"").add(SuFileInputStream(filePath)).exec()
                Log.d("AppLog", "success pushing apk:${apkSource.fileName} ? ${result.isSuccess}")
            }
```

But when I reach the line of "Shell.su", it gets stuck.

Attached here a sample project to show the issue. Also attached a bunch of split APK files that I got from Google News APKs.

[splitApks.zip](https://github.com/topjohnwu/libsu/files/3488795/splitApks.zip)
[splitApkInstallViaRoot.zip](https://github.com/topjohnwu/libsu/files/3488796/splitApkInstallViaRoot.zip)

Any idea what I'm doing wrong?
Is this the wrong syntax to use it?

**Comment by topjohnwu** [comment]
Github issues are not user support you know... it is for either providing feedback or bug reports.

Nevertheless, regarding the code you just showed, the `Shell.su(Inputstream)` method is directly feeding the input data directly into STDIN, which is not what the command is expecting. Please check out how to properly use `pm install-write`, this is not something to do with `libsu` is doing

**Comment by AndroidDeveloperLB** [comment]
It's ` pm install-write [-S BYTES] SESSION_ID SPLIT_NAME [PATH]` .
But how does this app do it via a stream? Odd. Maybe it only seem this way?

Anyway, thank you. I used this instead and it worked:

`                val result = Shell.su("pm install-write -S ${apkSource.fileSize} $sessionId \"${apkSource.fileName}\" \"$filePath\"").exec()
`

**Comment by AndroidDeveloperLB** [comment]
Please advice. What's the equivalent of the inputStream that the above code uses?

I think it's the only way for it to work on Android Q too, and not just versions before.

**Comment by AndroidDeveloperLB** [comment]
Please advice. What's the equivalent of the inputStream that the above code uses?
There is actually a way to send InputStream:

```
  install-write [-S BYTES] SESSION_ID SPLIT_NAME [PATH|-]
    Write an apk into the given install session.  If the path is '-', data
    will be read from stdin.  Options are:
      -S: size in bytes of package, required for stdin
```

I think it's the only way for it to work on Android Q too, and not just versions before.

Here, I think it should have been as such:

```
                val result = Shell.su("pm install-write -S ${apkSource.fileSize} $sessionId \"${apkSource.fileName}\" -")
                        .add(SuFileInputStream(filePath)).exec()
```

But it still get frozen on this phase.
Attached sample project.

[splitApkInstallViaRoot.zip](https://github.com/topjohnwu/libsu/files/3494050/splitApkInstallViaRoot.zip)


Please help.
If you wish, here's a StackOverflow question instead:

https://stackoverflow.com/q/57468292/878126
