### ISSUE TITLE
Request: add function to retry getting root 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/libsu#40]
Currently, we have to use something like that in case we were denied from getting root, and later got root manually from the root app:

`
val gotRoot = Shell.getCachedShell()?.isRoot == true || Shell.newInstance().isRoot
`

That's because `Shell.getShell()` tries to gain root only once, no matter how many times we call it.

**Comment by topjohnwu** [comment]
`Shell.getShell().close()` will close the global shell. The next time you call `getShell()`, a new shell will be created.

**Comment by AndroidDeveloperLB** [comment]
But the request is to try again. Not to close and re-open, which you say I should actually now write in 2 lines instead.

**Comment by AndroidDeveloperLB** [comment]
Do you say it's wrong to use what I wrote?
Please explain.
