### ISSUE TITLE
Can I use it without prompting root grant dialog?

### ISSUE THREAD

**Issue by imknown** [topjohnwu/libsu#43]
Hi, I just called `Shell.sh(cmd).exec().out`, and `cmd` is a normal command like `ls` that do not need root access. But the root dialog prompted on rooted device.

Any solutions to avoid this? Thx. :)

**Comment by topjohnwu** [comment]
It will ask for root no matter either you use `sh` or `su`. You can disable root in configuration flags, please refer to the Javadocs

**Comment by RevealedSoulEven** [comment]
You can use this btw
https://stackoverflow.com/questions/20932102/execute-shell-command-from-android
