### ISSUE TITLE
Possible bug: "Unable to create a shell!"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/libsu#46]
On this line:
```kt
val gotRoot = Shell.getCachedShell()?.isRoot == true || Shell.newInstance().isRoot
```

I got this error:

```
Caused by b.c.a.a: Unable to create a shell!
       at com.topjohnwu.superuser.Shell.newInstance(Shell.java:278)
       at com.topjohnwu.superuser.Shell.newInstance(Shell.java:239)

Caused by java.io.IOException: Shell timeout
       at com.topjohnwu.superuser.internal.ShellImpl.<init>(ShellImpl.java:144)
       at com.topjohnwu.superuser.internal.Factory.createShell(Factory.java:27)
       at com.topjohnwu.superuser.Shell.newInstance(Shell.java:255)
       at com.topjohnwu.superuser.Shell.newInstance(Shell.java:239)
```

This was on a bit older version of the library (2.5.0) but I don't see it being mentioned in the changelog.

Seems it occurs on Android 4.3, on RIM devices.

**Comment by topjohnwu** [comment]
It just mean your root solution isn't working properly, the shell is not established within the default timeout

**Comment by AndroidDeveloperLB** [comment]
What do you mean? That I should use try-catch?
Why does it throw an exception instead of just telling me it didn't get the root-access?

**Comment by topjohnwu** [comment]
No, the timeout simply means it is impossible to get a shell at all within the timeout,  it has nothing to do with root access or not. The timeout is there to make sure the thread creating the shell will not be blocked indefinitely

**Comment by AndroidDeveloperLB** [comment]
How do I reproduce it? 
Is it possible to return a value that says the result of timeout, instead of an exception? I don't even see it in the functions signatures, including inside their implementation :
https://github.com/topjohnwu/libsu/blob/master/core/src/main/java/com/topjohnwu/superuser/Shell.java
This way we will have to check the result on its various values.

Using Kotlin, I don't think it allows us to always notice those things, like on Java (which forces us to use try-catch) ... :(
On Kotlin, a nice alternative to exceptions, is to return a sealed class (similar to Enum, but not single instance). This way, the values can be : "Granted", "Denied", "TimeOut" , etc...

Can you please consider this change? 
Otherwise it's like saying I should use try-catch for every function call, without even knowing what I will catch, if at all...
