### ISSUE TITLE
Request: add UiThread AnyThread and WorkerThread wherever possible

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/libsu#47]
As the title says...

**Comment by topjohnwu** [comment]
Where to run the methods depends on the user of the library

**Comment by AndroidDeveloperLB** [comment]
So in places that both can be used, it should be AnyThread .

As for "depends", I can see in some of the docs that it doesn't really depend on developer that uses the library, as the library states:

> Get Shell via getCachedShell() or create new if required, returns via callback. If getCachedShell() does not return null, the callback will be invoked synchronously, or else it will call newInstance() in a background thread and invoke the callback on the main thread.

So, the callback is on the main thread, so it can be annotated with UiThread.

Meaning here:

```
    /**
     * The callback used in {@link #getShell(GetShellCallback)}.
     */
    public interface GetShellCallback {
        /**
         * @param shell the {@code Shell} obtained in the asynchronous operation.
         */
        void onShell(@NonNull Shell shell);
    }

```
