### ISSUE TITLE
Shell.su("echo 111").exec() blocked on abi aarch64

### ISSUE THREAD

**Issue by SheilaLundin** [topjohnwu/libsu#48]
"test" is not printed.
```
public class App extends Application {
    static {
        Shell.Config.setFlags(Shell.FLAG_REDIRECT_STDERR);
        Shell.Config.verboseLogging(BuildConfig.DEBUG);
        Shell.Config.addInitializers(BusyBoxInstaller.class);
    }
    ...
}

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
           ...
           Shell.su("echo 111").exec();
           Log.d("test", "test");
           ...
    }
}
```

**Comment by dooli22** [comment]
> "test" is not printed.
> 
> ```
> public class App extends Application {
>     static {
>         Shell.Config.setFlags(Shell.FLAG_REDIRECT_STDERR);
>         Shell.Config.verboseLogging(BuildConfig.DEBUG);
>         Shell.Config.addInitializers(BusyBoxInstaller.class);
>     }
>     ...
> }
> 
> public class MainActivity extends AppCompatActivity {
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>            ...
>            Shell.su("echo 111").exec();
>            Log.d("test", "test");
>            ...
>     }
> }
> ```
public class App extends Application {
    static {
        Shell.Config.setFlags(Shell.FLAG_REDIRECT_STDERR);
        Shell.Config.verboseLogging(BuildConfig.DEBUG);
        Shell.Config.addInitializers(BusyBoxInstaller.class);
    }
    ...
}

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
           ...
           Shell.su("echo 111").exec();
           Log.d("test", "test");
           ...
    }
}
