### ISSUE TITLE
Missing Large File Support (CONFIG_LFS) in Busybox

### ISSUE THREAD

**Issue by jimzrt** [topjohnwu/libsu#5]
Hi,
it seems that busybox (or at least mkfs.vfat applet) is compiled without Large File Support, so if I try to format a file created with truncate that is bigger than 2GB I get the following error:
`mkfs.vfat: lseek: Value too large for defined data type`
Also, if I use fdisk on a file that is bigger than 2GB I get this message:
`Unknown value(s) for: cylinders (settable in the extra functions menu)`
I don't know if that too relates to LFS, I just set the value manually in this case.

Would you maybe add the LFS flag when compiling busybox?
Thanks and great project, btw!

**Comment by topjohnwu** [comment]
Hello, I checked whether compiling with `LFS` enabled is possible; it turns out there is a small quirk in Android's bionic causing the building to fail.
Check this: http://lists.busybox.net/pipermail/busybox-cvs/2011-November/033019.html
