### ISSUE TITLE
Bug: targeting API 30, getting content of "/data/data/" returns a very small number of folders

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/libsu#52]
This simple code:

        thread {
            val result = Shell.su("ls -l \"/data/data/\"").exec().out
            Log.d("AppLog", "resulted lines of querying files on folder:${result.size}")
        }

    implementation "com.github.topjohnwu.libsu:core:2.5.1"

When I target API 29, it seems all fine.
When I target API 30, it has about 3 rows as result...

[iGHQDEjNdU.zip](https://github.com/topjohnwu/libsu/files/4866904/iGHQDEjNdU.zip)
[My Application.zip](https://github.com/topjohnwu/libsu/files/4866905/My.Application.zip)

Is it possible it's one of the restrictions on Android API 30?
But using adb via USB, it works fine...
How can I overcome this?

**Comment by topjohnwu** [comment]
This is not an issue with `libsu`, but I'll answer anyway.
You'll need to have the global namespace for accessing non-scoped storage. Enable it with setting the flag `Shell.FLAG_MOUNT_MASTER` in configs

**Comment by AndroidDeveloperLB** [comment]
Yes, sorry for that. It worked fine after using this flag.
Is it safe to call it on the application class?

Meaning this:

```kt
        Shell.Config.setFlags(Shell.FLAG_MOUNT_MASTER)
```

**Comment by PreciousWarrior** [comment]
```java
Shell.setDefaultBuilder(Shell.Builder.create().setFlags(Shell.FLAG_MOUNT_MASTER));
```

Add this at the start and it should fix the issue.

**Comment by AndroidDeveloperLB** [comment]
@PreciousWarrior Yes, I think it changed later.
