### ISSUE TITLE
NDK equivilant

### ISSUE THREAD

**Issue by mgood7123** [topjohnwu/libsu#53]
is there an NDK equivilant for C++ use?

**Comment by mgood7123** [comment]
as i came up with this small library https://github.com/mgood7123/libsu however it is assumably nowhere near the scale of this one

**Comment by topjohnwu** [comment]
@mgood7123 you should NOT do this!
Instead you should write binaries in C++, and call the binaries through `libsu`'s Java layer to get data.
Or you have to wait for me to implement `libsu` with actual Java code running in root support and use JNI with that.
