### ISSUE TITLE
suFile gets stuck

### ISSUE THREAD

**Issue by Tiefkuehlpizze** [topjohnwu/libsu#62]
Hi,
I'm working on an app that extracts data from an tar file using apache commons' implementation for that.

I'm now stuck for days because there is a nasty issue on the suFile implementation and maybe someone can tell what's going on:
So this is the log output:
Note: I overwrote the filepath manually to see, if it's related to the filename, but here you can see, it isn't.
```
// … next file
D/SHELL_IN: __F_='/data/user/0/com.example.org/app_webview/Local Storage/leveldb/000016.ldb'
    [ -b "$__F_" ]
D/SHELL_IN: __F_='/data/user/0/com.example.org/app_webview/Local Storage/leveldb/000016.ldb'
    [ -d "$__F_" ]
D/SHELL_IN: __F_='/data/user/0/com.example.org/app_webview/Local Storage/leveldb/000016.ldb'
    echo -n > "$__F_"
D/SHELLIO: dd bs=88093 count=1 >> '/data/user/0/com.example.org/app_webview/Local Storage/leveldb/000016.ldb' 2>/dev/null; echo
// … next file
D/SHELL_IN: __F_='/data/user/0/com.example.org/app_webview/Local Storage/leveldb/000016.ldb'
    [ -b "$__F_" ]
```

According to the log, it's stuck on the `[ -b "$__F" ]` command that checks if my (not existing, but it doesn't matter) file is a block device.
Due to the fact, that I'm extracting a bunch of files, I think, it's related to the high frequency of commands send to my shell instance.

Here's a short code snippet, to better understand, what I'm doing: 
```java
 TarArchiveEntry tarEntry;
        while ((tarEntry = archive.getNextTarEntry()) != null) {
if (tarEntry.isFile()) {
    final File targetFile = new File(targetDir, tarEntry.getName());
    //try (SuFileOutputStream fos = new SuFileOutputStream(SuFile.open(targetDir,  tarEntry.getName()))) {
    String name = tarEntry.getName();
    if(name.contains("000014"))
        name = "app_webview/Local Storage/leveldb/000016.ldb";
    try (SuFileOutputStream fos = new SuFileOutputStream(SuFile.open(targetDir,  name))) {
          IOUtils.copy(archive, fos, TarUtils.BUFFERSIZE);
    }
}
```
When I insert a `Thread.sleep(1000);) in the loop, it works. 100ms is not enough.

Tested on Android API 27 x86 Emulator 

Funny enough, when I used the _File_ type as parameter, the execution stopped in this constructor:
```java
    SuFile(@NonNull File file) {
        super(file.getAbsolutePath());
        CMDs = new String[2];
        CMDs[0] = "__F_='" + file.getAbsolutePath() +  "'";
    }
```
On the line `CMDs[0] = "__F_='" + file.getAbsolutePath() +  "'";` and sometimes the app gets killed by the system server because Out of Memory issues. During execution there were 600 MB available…

Very weird. I cannot see anything wrong on the string.

**Comment by topjohnwu** [comment]
Please try out 3.1.0, it should fix this issue
