### ISSUE TITLE
Checking if the shell has root can actually lock the thread to get the result, as it asks to get root

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/libsu#67]
The docs about `Shell.rootAccess()` says:

> Return whether the global shell has root access.

However, when I run it, it actually requests root, making it wait on the current thread till it gets result:

```kt
        findViewById<View>(R.id.button).setOnClickListener {
            Log.d("AppLog", "checking if we had root")
            //this should be returned right away:
            Log.d("AppLog", "has root?${Shell.rootAccess()}")
            Log.d("AppLog", "done checking")
        }
```

See attached:
[SSBCl3p2ly.zip](https://github.com/topjohnwu/libsu/files/5758872/SSBCl3p2ly.zip)
[My Application.zip](https://github.com/topjohnwu/libsu/files/5758873/My.Application.zip)

**Comment by AndroidDeveloperLB** [comment]
I think the correct one to use should be:

```kt
fun hasRoot() = Shell.getCachedShell()?.isRoot == true
```

**Comment by franciscofranco** [comment]
That's the point, it should block the thread, it's a blocking call that's why you shouldn't call it on the UI thread...

**Comment by AndroidDeveloperLB** [comment]
@franciscofranco Was I correct though, of checking if we already got root properly, which should be safe on the UI thread?

**Comment by AndroidDeveloperLB** [comment]
The docs are:
"Return whether the global shell has root access."

**Comment by AndroidDeveloperLB** [comment]
If it just returns if we got it, it shouldn't be blocking. It should just return the value.
That's what's wrong. The docs are misleading.

**Comment by AndroidDeveloperLB** [comment]
Instead of just "return" it should say "acquires root on the global shell if needed, and returns true iff granted".

**Comment by topjohnwu** [comment]
@AndroidDeveloperLB the docs is updated with more info, I'll release a new build soon.
In the meantime, check the source code `Shell.java`

**Comment by AndroidDeveloperLB** [comment]
It now says for "rootAccess" :

```
    /**
     * {@code Shell.getShell().isRoot()}
     * <p>
     * Please refer to {@link #getShell()} for info about concerns on blocking.
     */
```


And for "getShell" it says:

```
    /**
     * Get the main shell instance.
     * <p>
     * If {@link #getCachedShell()} returns null, the default {@link Builder} will be used to
     * construct a new {@code Shell}.
     * <p>
     * Unless already cached, this method blocks until the main shell is created.
     * The process could take a very long time (e.g. root permission request prompt),
     * so be extra careful when calling this method from the main thread!
     * <p>
     * A good practice is to "preheat" the main shell during app initialization
     * (e.g. the splash screen) by either calling this method in a background thread or
     * calling {@link #getShell(GetShellCallback)} so subsequent calls to this function
     * returns immediately.
     * @return the cached/created main shell instance.
     * @see Builder#build()
     */

```
So I think this is good about explanation of the issue.

It doesn't explain now though what `rootAccess` does. Instead it tells you what's in the code of it, and to go to somewhere else in the docs to understand what the code is.

Is it recommended on JavaDocs to just say "this is the code of the function, and look somewhere else to understand what this code means" ?

**Comment by topjohnwu** [comment]
I believe `Shell.getShell().isRoot()` is much better than copying the exact same text from `getShell` and paste it there...

**Comment by AndroidDeveloperLB** [comment]
For concerns and important notes, as they might be shared between multiple functions, sure. 
For understanding what the function does in general and/or what it's meant for, I don't think so.
