### ISSUE TITLE
Need to check for null return, or avoid it somehow

### ISSUE THREAD

**Issue by developer79433** [topjohnwu/libsu#7]
ShellUtils.fastCmd can return null. At the moment this causes its caller to crash.

In order to avoid a java.lang.NullPointerException, either this code needs to check for such a null return value, or ShellUtils.fastCmd should be modified so it always returns a valid string (never null), or ShellUtils.fastCmd should raise an exception instead of returning null when it encounters a fatal error.

https://github.com/topjohnwu/libsu/blob/8072a45c8e550b6f3aca6db2bb3f5f097bfaaec9/superuser/src/main/java/com/topjohnwu/superuser/internal/ShellImpl.java#L162

**Comment by developer79433** [comment]
Ok, I see what you're doing. ShellUtils.isValidOutput detects no lines of output, or all lines of output being empty strings, and Shell Utils.fastCmd in that case returns null. So this just means that the command output nothing other than blank lines.
It's possible, but not very likely in my opinion, that the command "echo $PATH" output no lines or only blank lines. I'd expect PATH to always have a value (?).
More likely is the command couldn't be executed, for some deeper reason, which perhaps should have caused an exception to be thrown. I'll investigate that possibility.

**Comment by topjohnwu** [comment]
Starting from v2.0, `libsu` will ever return null 👍
