### ISSUE TITLE
Daemon when use System.loadLibrary

### ISSUE THREAD

**Issue by MrPictYT-art** [topjohnwu/libsu#70]
Hi,

Thanks For Your Great Project, It Helps Me alot
i try creating app again with source from example, in AIDLService when i click the button Daemon it seems not getting any result

i checked it on Logcat but it seems the command is getting result like this :
`(LIBSU_VERBOSE_LOGGING=1 CLASSPATH=/data/user_de/0/com.eara.manager/cache/main.jar /proc/20411/exe  /system/bin --nice-name=com.eara.manager:root com.topjohnwu.superuser.internal.IPCMain com.eara.manager/com.eara.manager.AIDLService com.topjohnwu.superuser.ipc.IPCServer)&`

Without getting any continue like **daemon : service Connected**

**Comment by MrPictYT-art** [comment]
After remove native loadLibrary and the function it working fine
![image](https://user-images.githubusercontent.com/60846364/107160634-04d04380-69ca-11eb-987f-6b5e4fbc34d0.png)

**Comment by topjohnwu** [comment]
@MrPictYT-art have you tried the example project, does it work for you?

**Comment by MrPictYT-art** [comment]
> @MrPictYT-art have you tried the example project, does it work for you?

same result

**Comment by MrPictYT-art** [comment]
seems it's my fault, I trying again the sample project and its working, Thankyou
