### ISSUE TITLE
ls not listing all root folders

### ISSUE THREAD

**Issue by TylerOlson** [topjohnwu/libsu#75]
I'm trying to access the data folders yet when I `cd` into `/data/data/` and `ls` I only get my app's folder and `com.google.android.gms`

When I connect via ADB and do the same thing with root I get the full list. No idea what I'm doing wrong.

Here is my code
```
Shell.su("cd /data/data").exec()
val result: Shell.Result = Shell.su("ls").exec()

Log.e(TAG, "Checking")
Log.e(TAG, result.out.size.toString())
result.out.forEach {
    Log.e(TAG, it)
}
```

**Comment by topjohnwu** [comment]
It is due to mount namespace settings, nothing to do with libsu

**Comment by TylerOlson** [comment]
[I found out it's due to Android 11's storage updates.](https://android.stackexchange.com/questions/231481/android-11-cant-see-contents-of-android-data-even-with-root/231482#231482?newreg=f100423599714220aa923825d3484c8c) My solution was just to lower my target to Android 10 instead of 11.

**Comment by PreciousWarrior** [comment]
```java
Shell.setDefaultBuilder(Shell.Builder.create().setFlags(Shell.FLAG_MOUNT_MASTER));
```

Add this at the start and it should fix the issue.
