### ISSUE TITLE
Doesn't supported on Android 11

### ISSUE THREAD

**Issue by Dhruvkanani** [topjohnwu/libsu#81]
I tried to run a shell command to remove a file at path /data/data/<other package except the package of itself>/
, But it doesn't worked on Android 11. However it was working till Android 10. 
Using the apps like Termux and MT Manager i was able to execute the shell at above path.
Thank you in advance and it will be a great help if you give me a solution to execute shell at above path.

**Comment by BryanGIG** [comment]
maybe #75

**Comment by Dhruvkanani** [comment]
Thank you. It solved my issue
