### ISSUE TITLE
startRootServer getting block

### ISSUE THREAD

**Issue by ThinhVu** [topjohnwu/libsu#82]
in `startRootServer`

```
synchronized (this) {
    Shell.su("(" + cmd + ")&").exec();
    // Wait for broadcast receiver
    wait();
}
```

`wait` method block the thread and doesn't give any response.

**Comment by hotstu** [comment]
The RootService makes callback by using Broadcast, but there are some logical hole when starting RootService that Never happen

**Comment by topjohnwu** [comment]
The root service management code is fully rewritten from scratch in 3.2.0, it no longer depends on thread blocking
