### ISSUE TITLE
jitpack not working.

### ISSUE THREAD

**Issue by NabsiYa** [topjohnwu/libsu#83]
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.topjohnwu.libsu:core:3.1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/topjohnwu/libsu/core/3.1.2/core-3.1.2.pom
       - https://repo.maven.apache.org/maven2/com/github/topjohnwu/libsu/core/3.1.2/core-3.1.2.pom
       - https://jcenter.bintray.com/com/github/topjohnwu/libsu/core/3.1.2/core-3.1.2.pom
     Required by:
         project :app
   > Could not find com.github.topjohnwu.libsu:service:3.1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/topjohnwu/libsu/service/3.1.2/service-3.1.2.pom
       - https://repo.maven.apache.org/maven2/com/github/topjohnwu/libsu/service/3.1.2/service-3.1.2.pom
       - https://jcenter.bintray.com/com/github/topjohnwu/libsu/service/3.1.2/service-3.1.2.pom
     Required by:
         project :app
   > Could not find com.github.topjohnwu.libsu:io:3.1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/topjohnwu/libsu/io/3.1.2/io-3.1.2.pom
       - https://repo.maven.apache.org/maven2/com/github/topjohnwu/libsu/io/3.1.2/io-3.1.2.pom
       - https://jcenter.bintray.com/com/github/topjohnwu/libsu/io/3.1.2/io-3.1.2.pom
     Required by:
         project :app
   > Could not find com.github.topjohnwu.libsu:busybox:3.1.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/topjohnwu/libsu/busybox/3.1.2/busybox-3.1.2.pom
       - https://repo.maven.apache.org/maven2/com/github/topjohnwu/libsu/busybox/3.1.2/busybox-3.1.2.pom
       - https://jcenter.bintray.com/com/github/topjohnwu/libsu/busybox/3.1.2/busybox-3.1.2.pom
     Required by:
         project :app

**Comment by kur0yama** [comment]
i'm sorry but how do you managed to fix this issue?

**Comment by BryanGIG** [comment]
> i'm sorry but how do you managed to fix this issue?

set your settings.grandle like this, it's working fine on me

![image](https://user-images.githubusercontent.com/60846364/129476515-2f9ac7a0-8568-4d23-baf9-452b502086f1.png)
