### ISSUE TITLE
Shell.su not respond on ADB SHELL command

### ISSUE THREAD

**Issue by TexLui** [topjohnwu/libsu#88]
Install adb from Magisk Modules
connect another android device to usb port

### run:  _output = Shell.su("adb devices").exec().getOut();_
Result :
**adb devices
List of devices attached
15b138c8184a7bcb        device**

### run : _output = Shell.su("adb shell getenforce").exec().getOut();_
Result:
**the command not respond and wait forever**

**Comment by topjohnwu** [comment]
There is no adb on Android

**Comment by TexLui** [comment]
Great
