### ISSUE TITLE
some function seems not working for emulator ldplayer

### ISSUE THREAD

**Issue by MikaCybertron** [topjohnwu/libsu#90]
some function libsu like function SuFile and SuRandomAccess not working on ldplayer, please fix it!!

**Comment by RevealedSoulEven** [comment]
I knew @MikaCybertron can do that himself. If I ain't wrong you're modder at platinmods right?

**Comment by MikaCybertron** [comment]
> I knew @MikaCybertron can do that himself. If I ain't wrong you're modder at platinmods right?

haha yeah
