### ISSUE TITLE
How can I make a Shell.Result waiting for a result?

### ISSUE THREAD

**Issue by RevealedSoulEven** [topjohnwu/libsu#93]
I'm making an app for root devices using libsu (by TopJohnwu)

I wanted to ask if anyone knows how can I wait for the Shell.su function to return a value and assign the variable?

Like I took a String x = "";

Now I want that when Shell.su("sleep 5; echo 100").submit(); is true it will assign the variable to String x;

Now as you can see I'll wait for sometime so I need to assign the variable after getting the final output.

Btw I don't want to wait but the shell command I'll be using takes 2-3 seconds to execute or more.

So I need a help regarding it.

Thank you!

**Comment by RevealedSoulEven** [comment]
`Shell.su("for i in $(seq 5); do echo $i; sleep 1; done")
    .to(callbackList)
    .submit(result -> `updateUI(result));`

As I see that here something similar is being used in the readme section. But the function updateUI is giving errors as it's not declared. Can I please know how to actually assign those output values into the ListString?

**Comment by topjohnwu** [comment]
Sorry, but I cannot understand your issue
