### ISSUE TITLE
Support for using RootService with a custom Shell instance

### ISSUE THREAD

**Issue by kdrag0n** [topjohnwu/libsu#96]
For dependency injection and synchronization purposes (e.g. to work around #84), it can be useful to use a custom Shell instance everywhere instead of using the global MainShell singleton. However, RootService is not compatible with this as RootServiceManager has a hard-coded call to `Shell.su`. There might also be other, more subtle dependencies on MainShell that I haven't noticed.

**Comment by topjohnwu** [comment]
Your wish has been granted: 88f384b39cd75ef165494917c67d9b0e7f0db498 and bceab53c9dc543f52a1ff1251b053844aa7d6180

**Comment by kdrag0n** [comment]
Perfect, thanks so much!
